Update FC submodule with BOOST_COMPONENTS fix
Fixes link error: undefined reference to boost::program_options

The FC commit 95e4d66 inadvertently cleared the parent's BOOST_COMPONENTS
variable, causing program_options and other boost libraries to be missing
from the link line.

See: https://gitlab.syncad.com/hive/fc/-/merge_requests/8